# Generated by Django 5.0.2 on 2024-06-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=222)),
                ('text', models.TextField()),
                ('numbers', models.IntegerField()),
                ('ismi', models.CharField(max_length=300)),
            ],
        ),
        migrations.RenameField(
            model_name='profil',
            old_name='rasm',
            new_name='rasmi',
        ),
    ]
