# Generated by Django 5.0.2 on 2024-06-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_email_rename_rasm_profil_rasmi'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='nom',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
